name: 'Composite action'
description: 'Print stuff'
inputs:
  env:
    description: 'current environment'
    required: true
  component_name:
    description: 'current component'
    required: true
  component_property_name:
    description: 'name of the GHA variable that holds the component proprty'
    required: true
  component_property_value:
    description: 'value of component property'
    required: true
  secret_value:
    required: true
runs:
  using: "composite"
  steps:
    - name: print inputs
      shell: bash
      run: |
        echo "env: ${{ inputs.env }}"
        echo "component_name: ${{ inputs.component_name }}"
        echo "component_property_name: ${{ inputs.component_property_name }}"
        echo "component_property_value: ${{ inputs.component_property_value }}"
        echo "secret value: ${{ inputs.secret_value }}"
        echo "transformed secret value: ${{ inputs.secret_value }}"|sed 's/I/U/g'
    - name: print inputs as env
      env:
        env: ${{ inputs.env }}
        component_name: ${{ inputs.component_name }}
        component_property_name: ${{ inputs.component_property_name }}
        component_property_value: ${{ inputs.component_property_value }}
        secret_value: ${{ inputs.secret_value }}
      shell: bash
      run: |
        echo "env: $env"
        echo "component_name: $component_name"
        echo "component_property_name: $component_property_name"
        echo "component_property_value: $component_property_value"
        echo "secret value: $secret_value"
        echo "transformed secret value: $secret_value"|sed 's/I/U/g'

