name: playground

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    strategy:
      matrix:
        variable_holder:
        - name: vh1
          variable: var1
        - name: vh2
          variable: var2
    runs-on: ubuntu-latest
    environment: "env1"
    outputs:
      out_vh1: ${{ steps.gen_outputs.outputs.out_vh1 }}
      out_vh2: ${{ steps.gen_outputs.outputs.out_vh2 }}
    steps:
      - id: gen_outputs
        name: Generate outputs
        run: |
          echo out_${{ matrix.variable_holder.name }}=${{ vars[matrix.variable_holder.variable]}} >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs:
      - job1
    steps:
      - name: Print variables from job1
        run: |
          echo "vh1 -> ${{ needs.job1.outputs.out_vh1 }}"
          echo "vh2 -> ${{ needs.job1.outputs.out_vh1 }}"

