name: playground

on:
  push:
    branches: [ "main" ]

jobs:
  reusable-workflow:
    strategy:
      matrix:
        environment: [env1, env2]
    uses: ./.github/workflows/reusable-workflow.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment }}
